export type ForIonicBase7Poff = {
  code: string;
  m_code: string;
  yday: string;
  month: string;
  kabusu: string;
  yutai: string;
  yutai_syubetsu: string;
  kosyo_value: string;
  gl_value: string;
  public_value: string;
  rimawari: string;
  nkc?: string | null;
  kbc?: string | null;
  rtc?: string | null;
  sbc?: string | null;
  gmc?: string | null;
  mtc?: null;
  mtct?: string | null;
  mxc?: string | null;
  nkct?: string | null;
  kbct?: string | null;
  rtct?: string | null;
  sbct?: string | null;
  gmct?: string | null;
  mxct?: string | null;
  kbcv?: string | null;
  rtcv?: string | null;
  sbcv?: string | null;
  gmcv?: string | null;
  mtcv?: string | null;
  nkg?: string | null;
  kbg?: string | null;
  rtg?: string | null;
  sbg?: string | null;
  gmg?: string | null;
  mtg?: string | null;
  mxg?: string | null;
  max_gl?: string | null;
  max_pgl?: string | null;
  b1y_vkabuka: string;
  b2y_vkabuka: string;
  haito?: string | null;
  ahaito: string;
  riron_gyaku: string;
  gyaku_days: string;
  name?: string | null;
  kabuka?: string | null;
  vol: string;
  taisyaku: string;
  kisei1?: string | null;
  kisei2?: string | null;
  d_content?: string | null;
  d_table?: string | null;
  d_acontent?: string | null;
  d_curl?: string | null;
  d_logo?: string | null;
  d_kenri?: string | null;
  nvol?: string | null;
  nkako: string;
  kvol?: string | null;
  kp: string;
  kcmvol?: null;
  kkako: string;
  rvol?: string | null;
  rls?: string | null;
  rkako: string;
  gvol?: string | null;
  gls?: string | null;
  gkako: string;
  svol?: string | null;
  sls?: string | null;
  skako: string;
  xvol?: string | null;
  xls?: string | null;
  xkako: string;
  mvol?: string | null;
  mls?: string | null;
  mp: string;
  mkako: string;
  max5_gyaku: string;
  avg5_gyaku: string;
  recent_gyaku: string;
  recent_gyaku_date: string;
  recent_gyaku_kisei: string;
  riron_max_gyaku: string;
  agl_value: string;
  realtime_kisei_status?: string | null;
  realtime_kisei_regulation?: string | null;
  realtime_kisei_date1?: string | null;
  realtime_kisei_date2?: string | null;
  kabuka2: string;
  name2: string;
  name2kana: string;
  kenri_code: string;
  c_nissu: string;
  nc_nissu: string;
  kanrikaisu: string;
  kenribi: string;
  kenri_tsuki: string;
  kenri_oti: string;
  sbi_flying: string;
  sbi_yoyaku: string;
  sbi_start: string;
  rakuten_yoyaku: string;
  rakuten_start: string;
  monex_yoyaku: string;
  rt_hantei: string;
  st_hantei: string;
  gt_hantei: string;
  mt_hantei: string;
  b1y_kenri: string;
  b2y_kenri: string;
  b3y_kenri: string;
  b4y_kenri: string;
  b5y_kenri: string;
  b1y_kenrioti: string;
  b2y_kenrioti: string;
  b3y_kenrioti: string;
  b4y_kenrioti: string;
  b5y_kenrioti: string;
  haito_code: string;
};
